parameters:
    cisco.piwik.request.class:                CiscoSystems\PiwikBundle\Connection\Request
    cisco.piwik.client.class:                 CiscoSystems\PiwikBundle\Tracker\Client
    cisco.piwik.client.token:                 null
    cisco.piwik.connection.http.class:       CiscoSystems\PiwikBundle\Connection\HttpConnection
    cisco.piwik.connection.http.url:          null
    cisco.piwik.connection.piwik.class:       CiscoSystems\PiwikBundle\Connection\PiwikConnection
    cisco.piwik.connection.piwik.init:        false
    cisco.piwik.connectionstub.class:         CiscoSystems\PiwikBundle\Connection\StubConnection

services:
    cisco.piwik.request:
        class: '%cisco.piwik.request.class%'
    cisco.piwik.client:
        class: '%cisco.piwik.client.class%'
        arguments:
            - '@cisco.piwik.connection.http'
            - '%cisco.piwik.client.token%'

    cisco.piwik.connection.http:
        class: '%cisco.piwik.connection.http.class%'
        arguments:
            - %cisco.piwik.connection.http.url%

    cisco.piwik.connection.piwik:
        class: '%cisco.piwik.connection.piwik.class%'
        arguments:
            - '%cisco.piwik.connection.piwik.init%'

    cisco.piwik.connection.stub:
        class: '%cisco.piwik.connectionstub.class%'