parameters:
    cisco.piwik.client.class:                  CiscoSystems\PiwikBundle\Model\Client
    cisco.piwik.client.token:                   null
    cisco.piwik.client.url:                     null
    cisco.piwik.client.site_id:                 0
    cisco.piwik.client.format:                  null

    cisco.piwik.module.class:                   CiscoSystems\PiwikBundle\Model\Module

services:
    cisco.piwik.client:
        class: '%cisco.piwik.client.class%'
        arguments:
            - '%cisco.piwik.client.url%'
            - '%cisco.piwik.client.token%'
            - '%cisco.piwik.client.site_id%'
            - '%cisco.piwik.client.format%'

    cisco.piwik.module:
        class: '%cisco.piwik.module.class%'
        arguments:
            - '@cisco.piwik.client'